### ISSUE TITLE
GUI script broken

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#34]
* `sierralocal.py` doesn't exist any more
* replacing `subprocess` calls with direct calls to module

**Comment by ArtPoon** [comment]
`gui.py` script is unable to access algorithm XML in package directory:
```
Error: could not retrieve HIVDB XML
Unable to update HIVDB XML. Try manually downloading the HIVdb ASI2.
Error: could not retrieve APOBEC DRM data
Unable to update APOBEC DRMs. Try manually downloading the APOBEC DRM TSV into data/apobec.tsv
Traceback (most recent call last):
  File "main.py", line 173, in <module>
    main()
  File "main.py", line 162, in main
    count, time_elapsed = sierralocal(args.fasta, args.outfile, args.xml, args.skipalign, args.forceupdate)
  File "main.py", line 116, in sierralocal
    algorithm = HIVdb(path=xml, forceupdate=forceupdate)
  File "/usr/local/lib/python3.6/dist-packages/sierralocal/hivdb.py", line 63, in __init__
    self.root = xml.parse(self.xml_filename).getroot()
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/sierralocal/data/HIVDB_8.6.1.ca26d72f.xml'
```

**Comment by ArtPoon** [comment]
I resolved part of the problem by adding a `package_data` entry into the `distutils.core.setup()` command in `setup.py`, so the installer creates the `data` folder in `/usr/local/lib/python3.6/...`.  However, the permissions for the `data` folder are set to 755 - they have to be 777 in order for Python to be able to update the contents of this folder.  

I am also running into problems with the NucAmino binary - since this is not part of our distribution, it is not going to be copied over to the `/usr/local/lib/python3.6/...` folder.  Doing this requires `sudo` permissions and so on, and defeats the entire purpose of having a GUI script.

I am going to banish `gui.py` into its own development branch for now and focus on installation from source working.
