### ISSUE TITLE
testing pip3 install on fresh Ubuntu installation

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#35]
Ubuntu workstation running `4.15.0-32-generic`
* needed to run `sudo apt install python3-pip` in order to get `pip3`.  This also installed several other packages including `gcc` and `python3.6`:
  ```
  The following NEW packages will be installed:
  build-essential dh-python dpkg-dev fakeroot g++ g++-7 gcc gcc-7
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
  libasan4 libatomic1 libc-dev-bin libc6-dev libcilkrts5 libexpat1-dev
  libfakeroot libgcc-7-dev libitm1 liblsan0 libmpx2 libpython3-dev
  libpython3.6-dev libquadmath0 libstdc++-7-dev libtsan0 libubsan0
  linux-libc-dev make manpages-dev python-pip-whl python3-dev
  python3-distutils python3-lib2to3 python3-pip python3-setuptools
  python3-wheel python3.6-dev
  ```
* running `pip3 install sierralocal` ran successfully:
  ```
  Collecting sierralocal
    Downloading https://files.pythonhosted.org/packages/ce/a8/2501b1b3ad9b8abc7994b7ece3d325b3d765401c4ce7f5760bda765f5267/sierralocal-0.0.1.tar.gz (1.7MB)
    100% |████████████████████████████████| 1.7MB 1.2MB/s 
  Building wheels for collected packages: sierralocal
    Running setup.py bdist_wheel for sierralocal ... done
    Stored in directory: /home/art/.cache/pip/wheels/e1/2f/28/fab709a2a25b279a11774fbae50520a3dfeb370ad940e84c68
  Successfully built sierralocal
  Installing collected packages: sierralocal
  Successfully installed sierralocal-0.0.1
  ```
  but `sierralocal` is not in `PATH`:
  ```
  art@Lio:~$ sierralocal
  sierralocal: command not found
  ```
* this is because the package was downloaded to `~/.local`, which is not in the default `PATH` after Ubuntu 16.04.  Calling the script directly works fine.  We can also run the following:
  ```
  export PATH=~/.local/bin:$PATH
  ```
* I downloaded the `scripts/retrieve_hivdb_data.py` script and ran it:
  ```
  python3 retrieve_hivdb_data.py RT RT.fa
  ```
  to have some test data.  Here are the results:
  ```
  art@Lio:~$ sierralocal RT.fa
  Error: could not retrieve HIVDB XML. Updating...
  Unable to update HIVDB XML. Try running this script from the root directory.
  Error: could not retrieve APOBEC DRM data. Updating...
  Unable to update APOBEC DRMs. Try running this script from the root directory.
  Traceback (most recent call last):
    File "/home/art/.local/bin/sierralocal", line 11, in <module>
      sys.exit(main())
    File "/home/art/.local/lib/python3.6/site-packages/sierralocal/__init__.py", line 56, in main
      algorithm = HIVdb()
    File "/home/art/.local/lib/python3.6/site-packages/sierralocal/hivdb.py", line 47, in __init__
      self.root = xml.parse(self.xml_filename).getroot()
    File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
      tree.parse(source, parser)
    File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
      source = open(source, "rb")
  TypeError: expected str, bytes or os.PathLike object, not NoneType
  ```

**Comment by ArtPoon** [comment]
Next I'm going to see what happens if we run `sudo pip3 install sierralocal`.  First I ran `rm -rf ~/.local` to clean out the non-sudo installation, closed and reopened the Terminal app.  Next:
```
The directory '/home/art/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/art/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting sierralocal
Installing collected packages: sierralocal
Successfully installed sierralocal-0.0.1
art@Lio:~$ which sierralocal
/usr/local/bin/sierralocal
art@Lio:~$ sierralocal RT.fa
Error: could not retrieve HIVDB XML. Updating...
Unable to update HIVDB XML. Try running this script from the root directory.
```
We run into the same problem.

**Comment by ArtPoon** [comment]
I cloned the repo and tried running `main.py` to download these data files:
```
art@Lio:~/git/sierra-local/sierralocal$ python3 main.py ~/RT.fa
Traceback (most recent call last):
  File "main.py", line 173, in <module>
    main()
  File "main.py", line 162, in main
    count, time_elapsed = sierralocal(args.fasta, args.outfile, args.xml, args.skipalign, args.forceupdate)
  File "main.py", line 116, in sierralocal
    algorithm = HIVdb(path=xml, forceupdate=forceupdate)
TypeError: __init__() got an unexpected keyword argument 'forceupdate'
```

**Comment by ArtPoon** [comment]
Removed `/usr/local/` installation and went back to working with the `.local` pip3 installation.  Created a `/data` folder under `~/.local/lib/python3.6/site-packages/sierralocal`.  Running `sierralocal` from the parent directory `site-packages` enabled the script to download the HIVDB xml and APOBEC TSV files:
```
art@Lio:~/.local/lib/python3.6/site-packages$ sierralocal ~/RT.fa 
Error: could not retrieve HIVDB XML. Updating...
Updated HIVDB XML from https://hivdb.stanford.edu/assets/media/HIVDB_8.6.1.ca26d72f.xml into sierralocal/data/HIVDB_8.6.1.ca26d72f.xml
Error: could not retrieve APOBEC DRM data. Updating...
Updated APOBEC DRMs from https://hivdb.stanford.edu/assets/media/apobec-drms.5b7e1215.tsv into sierralocal/data/apobec.tsv
Traceback (most recent call last):
  File "/home/art/.local/bin/sierralocal", line 11, in <module>
    sys.exit(main())
  File "/home/art/.local/lib/python3.6/site-packages/sierralocal/__init__.py", line 56, in main
    algorithm = HIVdb()
  File "/home/art/.local/lib/python3.6/site-packages/sierralocal/hivdb.py", line 47, in __init__
    self.root = xml.parse(self.xml_filename).getroot()
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
I re-ran the script so that the XML loaded properly and ran into another problem:
```
art@Lio:~/.local/lib/python3.6/site-packages$ sierralocal ~/RT.fa 
sierralocal/data/HIVDB_8.6.1.ca26d72f.xml
Found NucAmino binary nucamino
Traceback (most recent call last):
  File "/home/art/.local/bin/sierralocal", line 11, in <module>
    sys.exit(main())
  File "/home/art/.local/lib/python3.6/site-packages/sierralocal/__init__.py", line 63, in main
    sequence_headers, sequence_scores, ordered_mutation_list, file_genes, sequence_lengths, file_firstlastNA, file_trims = scorefile(input_file, database, args.skipalign)
  File "/home/art/.local/lib/python3.6/site-packages/sierralocal/__init__.py", line 85, in scorefile
    aligner = NucAminoAligner()
  File "/home/art/.local/lib/python3.6/site-packages/sierralocal/nucaminohook.py", line 24, in __init__
    with open(Path('.')/'sierralocal'/'data'/'INIPrevalences.tsv','r') as INIfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sierralocal/data/INIPrevalences.tsv'
```
I have resolved this with a previous commit where I modified the `setup.py` script.  We need to update the scripts on PyPI accordingly.
