### ISSUE TITLE
Loss of speed in latest commit

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#36]
Somehow I've managed to make things a lot slower :-P
Before (commit c51f610..f4684e5):
```
art@orolo:~/git/sierra-local$ sierralocal test.fa
sierralocal/data/HIVDB_8.6.1.ca26d72f.xml
Found NucAmino binary nucamino-linux-amd64
AF013440.143P8W0.B.3 0 1
AF021278.JIDP2W0.B.14 2 0
Y16151.RO-BCI9.F.24 0 4
AY802655.CA9914.B.51 0 1
AF169102.Vent31B.B.60 0 6
AF153404.MilazzoTO1.B.69 0 3
100 sequences found in file test.fa.
sierralocal/data/HIVDB_8.6.1.ca26d72f.xml
Found HIVdb file sierralocal/data/HIVDB_8.6.1.ca26d72f.xml
Writing JSON to file test-local.json
Time elapsed: 1.8673 seconds (53.553 it/s)
```

After (last commit `cb737b4ef2a99bcbaaafdefecb06c5d15b09dddb`):
```
art@orolo:~/git/sierra-local$ sierralocal test.fa
HIVdb version 8.6.1
Found NucAmino binary nucamino-linux-amd64
test.fa
100 sequences found in file test.fa.
Writing JSON to file test_results.json
Time elapsed: 6.5858 seconds (15.356 it/s)
```

**Comment by ArtPoon** [comment]
Retraced my steps:
1. Wiped out `/usr/local/bin/sierralocal` and `/usr/local/lib/python3.6/dist-packages/sierralocal*`.
2. Ran `pip3 install sierralocal`.  The script will have trouble updating the XML files (see #35):
   ```
   art@orolo:~$ which sierralocal
   /home/art/.local/bin/sierralocal
   art@orolo:~$ sierralocal test.fa
   Error: could not retrieve HIVDB XML. Updating...
   Unable to update HIVDB XML. Try running this script from the root directory.
   Error: could not retrieve APOBEC DRM data. Updating...
   Unable to update APOBEC DRMs. Try running this script from the root directory
   ```
3. Downloaded tarball of release `v0.0.1` to my `Downloads` folder and unpacked.
4. Changed into this directory and ran same `pip3` binary to download the XMLs:
   ```
   art@orolo:~/Downloads/sierra-local-0.0.1$ sierralocal ../test.fa 
   Error: could not retrieve HIVDB XML. Updating...
   Updated HIVDB XML from https://hivdb.stanford.edu/assets/media/HIVDB_8.6.1.ca26d72f.xml into sierralocal/data/HIVDB_8.6.1.ca26d72f.xml
   Error: could not retrieve APOBEC DRM data. Updating...
   Updated APOBEC DRMs from https://hivdb.stanford.edu/assets/media/apobec-drms.5b7e1215.tsv into sierralocal/data/apobec.tsv
   Traceback (most recent call last):
     File "/home/art/.local/bin/sierralocal", line 11, in <module>
       sys.exit(main())
     File "/home/art/.local/lib/python3.6/site-packages/sierralocal/__init__.py", line 56, in main
       algorithm = HIVdb()
     File "/home/art/.local/lib/python3.6/site-packages/sierralocal/hivdb.py", line 47, in __init__
       self.root = xml.parse(self.xml_filename).getroot()
     File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
       tree.parse(source, parser)
     File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
       source = open(source, "rb")
   TypeError: expected str, bytes or os.PathLike object, not NoneType
   ```
5. Ran the same command again to trigger missing NucAmino error (fixed in commit ):
   ```
   art@orolo:~/Downloads/sierra-local-0.0.1$ sierralocal test.fa
   sierralocal/data/HIVDB_8.6.1.ca26d72f.xml
   Found NucAmino binary nucamino
   Traceback (most recent call last):
     File "/home/art/.local/bin/sierralocal", line 11, in <module>
       sys.exit(main())
     File "/home/art/.local/lib/python3.6/site-packages/sierralocal/__init__.py", line 63, in main
       sequence_headers, sequence_scores, ordered_mutation_list, file_genes, sequence_lengths, file_firstlastNA, file_trims = scorefile(input_file, database, args.skipalign)
     File "/home/art/.local/lib/python3.6/site-packages/sierralocal/__init__.py", line 87, in scorefile
       aligner.align_file(input_file)
     File "/home/art/.local/lib/python3.6/site-packages/sierralocal/nucaminohook.py", line 67, in align_file
       popen = subprocess.Popen(args)
     File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
       restore_signals, start_new_session)
     File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
       raise child_exception_type(errno_num, err_msg, err_filename)
   FileNotFoundError: [Errno 2] No such file or directory: './sierralocal/nucamino': './sierralocal/nucamino'
   ```

**Comment by ArtPoon** [comment]
There are many differences between @jzpero's last commit and the v0.0.1 release on PyPI:
```
5a6
> from sierralocal.subtyper import Subtyper
13c14
<         items = os.listdir(Path('./sierralocal/'))
---
>         items = os.listdir(Path(os.path.dirname(__file__)))
20,22d20
<         self.tripletTable = self.generateTable()
<         with open(Path('.')/'sierralocal'/'data'/'apobec.tsv','r') as csvfile:
<             self.ApobecDRMs = list(csv.reader(csvfile, delimiter='\t'))
24,31c22
<         with open(Path('.')/'sierralocal'/'data'/'INIPrevalences.tsv','r') as INIfile:
<             INI_prevalences = list(csv.reader(INIfile, delimiter='\t'))
<         self.INI_dict = {}
<         col_idx = ["Naive:%" in cell for cell in INI_prevalences[0]]
<         for row in INI_prevalences[1:]:
<             for i, col in enumerate(col_idx):
<                 if col:
<                     self.INI_dict[str(row[0]+row[1]+row[2]+INI_prevalences[0][i].split(':')[0])] = float(row[i])
---
>         self.tripletTable = self.generateTable()
33,40c24,25
<         with open(Path('.')/'sierralocal'/'data'/'PIPrevalences.tsv','r') as PIfile:
<             PI_prevalences = list(csv.reader(PIfile, delimiter='\t'))
<         self.PI_dict = {}
<         col_idx = ["Naive:%" in cell for cell in PI_prevalences[0]]
<         for row in PI_prevalences[1:]:
<             for i, col in enumerate(col_idx):
<                 if col:
<                     self.PI_dict[str(row[0]+row[1]+row[2]+PI_prevalences[0][i].split(':')[0])] = float(row[i])
---
>         with open(Path(os.path.dirname(__file__))/'data'/'apobec.tsv','r') as csvfile:
>             self.ApobecDRMs = list(csv.reader(csvfile, delimiter='\t'))
42,46c27,46
<         with open(Path('.')/'sierralocal'/'data'/'RTIPrevalences.tsv','r') as RTIfile:
<             RTI_prevalences = list(csv.reader(RTIfile, delimiter='\t'))
<         self.RTI_dict = {}
<         col_idx = ["Naive:%" in cell for cell in RTI_prevalences[0]]
<         for row in RTI_prevalences[1:]:
---
>         self.PI_dict = self.prevalence_parser('PIPrevalences.tsv')
>         self.RTI_dict = self.prevalence_parser('RTIPrevalences.tsv')
>         self.INI_dict = self.prevalence_parser('INIPrevalences.tsv')
> 
>         #initialize gene map
>         self.pol_start = 2085
>         self.gene_map = self.create_gene_map()
> 
>         #initialize Subtyper class
>         self.typer = Subtyper()
> 
>     def prevalence_parser(self, filename):
>         '''
>         Abstracted method for reading ARV prevalence TSV and returning a dictionary of these data.
>         '''
>         with open(Path(os.path.dirname(__file__))/'data'/filename,'r') as file:
>             table = list(csv.reader(file, delimiter='\t'))
>         var = {}
>         col_idx = ["Naive:%" in cell for cell in table[0]]
>         for row in table[1:]:
49,50c49,50
<                     self.RTI_dict[str(row[0]+row[1]+row[2]+RTI_prevalences[0][i].split(':')[0])] = float(row[i])
< 
---
>                     var[str(row[0]+row[1]+row[2]+table[0][i].split(':')[0])] = float(row[i])
>         return var
60c60
<             "./sierralocal/{}".format(self.nucamino_binary),
---
>             Path(os.path.dirname(__file__))/self.nucamino_binary,
71c71
<     Returns a dictionary with the amino acid position bounds for each gene in Pol, based on the HXB2 reference annotations.
---
>     Returns a dictionary with the AMINO ACID position bounds for each gene in Pol, based on the HXB2 reference annotations.
73,74c73
<     def gene_map(self):
<         pol_start = 2085
---
>     def create_gene_map(self):
80c79
<         convert = lambda x:int((x-pol_start)/3)
---
>         convert = lambda x:int((x-self.pol_start)/3)
91,98c90,94
<     def get_genes(self, firstAA):
<         start = 2085
<         gene_list = ['PR', 'RT', 'IN']
<         firstNA = [int((x - start)/3) for x in [2253, 2550, 4230, 5096]]
<         gene_present = [firstNA[i+1] > firstAA > x for i, x in enumerate(firstNA[:-1:])]
<         if any(gene_present):
<             return [gene_list[gene_present.index(True)]] #first TRUE only
<         return []
---
>     def get_gene(self, firstAA):
>         for gene, bounds in self.gene_map.items():
>             if bounds[0] <= firstAA <= bounds[1]:
>                 return gene
>         return None
104c100
<     def get_mutations(self, genemap, fastaFileName):
---
>     def get_mutations(self, fastaFileName):
110d105
<         tripletTable = self.generateTable()
130a126
> 
140,145d135
<                 pol_map = self.gene_map()
<                 for key in pol_map:
<                     low, hi = pol_map[key]
<                     if low <= firstAA <= hi:
<                         shift = low
<                         break
146a137,140
>                 gene = self.get_gene(firstAA)
>                 shift = self.gene_map[gene][0]
> 
>                 # parse mutation information:
163a158,160
>                 # subtype sequence
>                 subtype = self.typer.getClosestSubtype(sequence_list[idx])
> 
165,167c162,164
<                 trimLeft, trimRight = self.trimLowQualities(codon_list, shift, firstAA, lastAA, gene_muts, [], self.get_genes(firstAA)[0], row[0].split('.')[-1]) #TODO: get subtype via alignment
<                 if trimLeft + trimRight > 0:
<                     print(row[0], trimLeft, trimRight)
---
>                 trimLeft, trimRight = self.trimLowQualities(codon_list, shift, firstAA, lastAA, gene_muts, [], gene, subtype)
>                 # if trimLeft + trimRight > 0:
>                     # print(row[0], trimLeft, trimRight)
172c169
<                 file_genes.append(self.get_genes(firstAA))
---
>                 file_genes.append(gene)
175c172,173
<         assert len(file_mutations) == len(sequence_headers), "length of mutations dicts is not the same as length of names"
---
> 
>         assert len(file_mutations) == len(sequence_headers), "error: length of mutations dicts is not the same as length of names"
373,384c371
<         # key = str(position)+str(cons)+str(aa)+str(subtype)
< 
<         # if gene == 'IN' and key in self.INI_dict:
<         #     return self.INI_dict[key]
< 
<         # if gene == 'PR' and key in self.PI_dict:
<         #     return self.PI_dict[key]
< 
<         # if gene == 'RT' and key in self.RTI_dict:
<         #     return self.RTI_dict[key]
< 
<         key2 = str(position)+str(cons)+str(aa)+"All"
---
>         key2 = str(position)+str(cons)+str(aa)+subtype
395c382
<         return 0.0
---
>         return 100.0
413a401,403
> 
>     print(test.gene_map)
>     print(test.get_gene(594))
\ No newline at end of file
```

**Comment by ArtPoon** [comment]
Confirmed.  If I replace the above line with the following:
```python
subtype = header.split('.')[2]
```
then the processing time falls from 6.6514 seconds (15.196 sequences per s) to 1.9089 seconds (54.383 sequences per s).

Need to revise the manuscript to reflect this.
