### ISSUE TITLE
sierralocal fails on full-length pol sequence

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#45]
Testing on LANL subtype reference *pol* sequence set:
```
HIVdb version 8.6.1
Found NucAmino binary /usr/local/lib/python3.6/dist-packages/sierralocal/bin/nucamino-linux-amd64
Aligned pol.fa
Traceback (most recent call last):
  File "/usr/local/bin/sierralocal", line 11, in <module>
    exit_code = main.main()
  File "/usr/local/lib/python3.6/dist-packages/sierralocal/main.py", line 160, in main
    count, time_elapsed = sierralocal(args.fasta, args.outfile, args.xml, args.skipalign, args.forceupdate)
  File "/usr/local/lib/python3.6/dist-packages/sierralocal/main.py", line 132, in sierralocal
    file_trims, subtypes = scorefile(input_file, database, skipalign)
  File "/usr/local/lib/python3.6/dist-packages/sierralocal/main.py", line 75, in scorefile
    aligner.get_mutations(input_file, do_subtyping=True)
  File "/usr/local/lib/python3.6/dist-packages/sierralocal/nucaminohook.py", line 178, in get_mutations
    assert gene is not None, "Fatal error in get_mutations"
AssertionError: Fatal error in get_mutations
```

**Comment by ArtPoon** [comment]
In `tsv` output:
```
Sequence Name   POL FirstAA     POL LastAA      POL FirstNA     POL LastNA      POL Mutations   POL FrameShifts
Ref.A1.AU.03.PS1044_Day0.DQ676872       1       1003    1       3009    D5N:AAT
```
The first problem is that this full-length *pol* sequence includes the interval preceding PR, which fouls up the current parsing scheme.  The second problem is that if we exclude this 5' interval, there is still an indexing issue when we attempt to subtype the sequence because the reference sequences are trimmed to PR-RT.
I think the solution is to switch to the NucAmino JSON output and parse this more comprehensive information to extract the aligned PR-RT sequence.

**Comment by ArtPoon** [comment]
NucAmino JSON field `NucleicAcidsLine` contains the following:
```
TTTTTTAGGGAAAATTTGGCCTTCCAGCAAGGGGAGGCCAGGAAATTTCCCTCAGAGCAGACCAGAGCCAACAGCCCCACCAGCGGAGCTCTTTGGGATGGGGGAAGAGATAACCTCCCC   TCCGAAGCAGGAGCAGAAGGACAAGGAA
TTTTTTAGGGAAAATTTGGCCTTCCAGCAAGGGGAGGCCAGGAAATTTCCCTCAGAGCAGACCAGAGCCAACAGCCCCACCAGCGGAGCTCTTTGGGATGGGGGAAGAGATAACCTCCCCTCCGAAGCAGGAGCAGAAGGACAAGGAACAGGTCCCACC
```
An excerpt of the original, unaligned sequence is displayed along the bottom.  Note this interval largely precedes PR in the pol sequence, but I'm including it as an example of how indels are handled.

**Comment by ArtPoon** [comment]
Now directly parsing JSON output as of commit 6c68f7ae.
Script is not outputting results for other genes (i.e., only `PI` scores are being reported).  Need to resolve this before closing issue.

**Comment by ArtPoon** [comment]
Almost there. Dealing with 24 discordant cases in PR batch.  Seems to be handling of ambiguous residues.  Also need to stop script from attempting to call RT resistance on PR sequences.

**Comment by ArtPoon** [comment]
Confirmed. sierra-client will code two amino acids at a position, *e.g.*, `AY900873` E35ND but not G48AGSCW (G48X).

**Comment by ArtPoon** [comment]
Restored triplet translation function, this seems to ameliorate the problem.  Closing and writing up other problems as a separate issue.
