### ISSUE TITLE
Installation from PyPI (pip) failed on fresh Ubuntu workstation

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#51]
Looks like a user permissions problem:
```
searching path /usr/local/lib/python3.6/dist-packages/sierralocal/data/HIVDB*.xml
Error: could not find local copy of HIVDB XML, attempting download...
Unable to update HIVDB XML. Try manually downloading the HIVdb ASI2.
[Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/sierralocal/data/HIVDB_8.7.9e470b87.xml'
/usr/local/lib/python3.6/dist-packages/sierralocal/data/apobec.tsv
Error: could not retrieve APOBEC DRM data
Unable to update APOBEC DRMs. Try manually downloading the APOBEC DRM TSV into data/apobec.tsv
Traceback (most recent call last):
  File "/usr/local/bin/sierralocal", line 11, in <module>
    exit_code = main.main()
  File "/usr/local/lib/python3.6/dist-packages/sierralocal/main.py", line 174, in main
    cleanup=args.cleanup, forceupdate=args.forceupdate)
  File "/usr/local/lib/python3.6/dist-packages/sierralocal/main.py", line 107, in sierralocal
    algorithm = HIVdb(path=xml, forceupdate=forceupdate)
  File "/usr/local/lib/python3.6/dist-packages/sierralocal/hivdb.py", line 76, in __init__
    self.root = xml.parse(str(self.xml_filename)).getroot()
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'None'
```

Installation history:
```
sudo apt install python3-pip
sudo -H python3 -m pip install --index-url https://test.pypi.org/simple/ sierralocal
```

**Comment by ArtPoon** [comment]
@WilliamZekaiWang successfully did a fresh install on a naive Ubuntu workstation
closing as resolved / no repro
