### ISSUE TITLE
sierralocal fails on macOS High Sierra with Python 3.7.4

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#57]
```
Elzar:~ artpoon$ sierralocal
Traceback (most recent call last):
  File "/usr/local/bin/sierralocal", line 7, in <module>
    from sierralocal import main
  File "/usr/local/lib/python3.7/site-packages/sierralocal/main.py", line 1, in <module>
    from sierralocal import score_alg
  File "/usr/local/lib/python3.7/site-packages/sierralocal/score_alg.py", line 1, in <module>
    from sierralocal.hivdb import HIVdb
  File "/usr/local/lib/python3.7/site-packages/sierralocal/hivdb.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by ArtPoon** [comment]
Forgot to include `requests` as a dependency.  Installing this via `pip3` resolves the issue.
