### ISSUE TITLE
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/sierra-local#67]
`getchildren` was deprecated in Python 3.2 and removed in 3.9:
https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren

**Comment by ArtPoon** [comment]
Resolved in branch `iss67`, but now running into another error:
```python
art@Wernstrom sierra-local % python3 sierralocal/main.py tests/hxb2-pr.fa
searching path /usr/local/lib/python3.10/site-packages/sierralocal/data/HIVDB*.xml
searching path /usr/local/lib/python3.10/site-packages/sierralocal/data/apobec*.tsv
HIVdb version 8.8
Found NucAmino binary /usr/local/lib/python3.10/site-packages/sierralocal/bin/nucamino-darwin-amd64
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x11886aa, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0xa0 fp=0x7ff7bfeff870 sp=0x7ff7bfeff850 pc=0x102deb0
runtime.goenvs(...)
	/usr/local/go/src/runtime/os_darwin.go:108
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:492 +0x22e fp=0x7ff7bfeff8b0 sp=0x7ff7bfeff870 pc=0x1030c1e
runtime.rt0_go(0x7ff7bfeff8e8, 0x8, 0x7ff7bfeff8e8, 0x0, 0x1000000, 0x8, 0x7ff7bfeffab8, 0x7ff7bfeffb06, 0x7ff7bfeffb0c, 0x7ff7bfeffb0f, ...)
	/usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff8b8 sp=0x7ff7bfeff8b0 pc=0x105ea5b
Traceback (most recent call last):
  File "/Users/art/git/sierra-local/sierralocal/main.py", line 190, in <module>
    main()
  File "/Users/art/git/sierra-local/sierralocal/main.py", line 178, in main
    count, time_elapsed = sierralocal(args.fasta, args.outfile, xml=args.xml, tsv=args.tsv,
  File "/Users/art/git/sierra-local/sierralocal/main.py", line 122, in sierralocal
    file_trims, subtypes = scorefile(input_file, algorithm)
  File "/Users/art/git/sierra-local/sierralocal/main.py", line 47, in scorefile
    result = aligner.align_file(input_file)
  File "/usr/local/lib/python3.10/site-packages/sierralocal/nucaminohook.py", line 180, in align_file
    result = json.load(self.reader(p.stdout))
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by GopiGugan** [comment]
> Resolved in branch `iss67`, but now running into another error:

Ran into this issue before. This issue is related to the `nucamino-darwin-amd64` binary. Needs to be recompiled

**Comment by ArtPoon** [comment]
Recompiled on user side or on repo side?

**Comment by GopiGugan** [comment]
> Recompiled on user side or on repo side?

We can compile it again and upload the binary to the repo

**Comment by ArtPoon** [comment]
Ok so is the problem that the `nucamino` source code has changed?

**Comment by GopiGugan** [comment]
> Ok so is the problem that the `nucamino` source code has changed?

No, I think there may have been an issue when it was previously compiled. I didn't run into any issues with the `nucamino-linux-amd64` or `nucamino-windows-amd64.exe`. Only ran into an issue with the `nucamino-darwin-amd64` binary:

```console
gopi:sierra-local gopi$ ./sierralocal/bin/nucamino-darwin-amd64 
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x11886aa, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0xa0 fp=0x7ff7bfeff6f0 sp=0x7ff7bfeff6d0 pc=0x102deb0
runtime.goenvs(...)
	/usr/local/go/src/runtime/os_darwin.go:108
```

**Comment by ArtPoon** [comment]
Let's update the binaries please

**Comment by ArtPoon** [comment]
I need to pull and try to repro this issue before closing
