### ISSUE TITLE
Issue when testing `align_file` method of `NucAminoAligner`

### ISSUE THREAD

**Issue by SandeepThokala** [PoonLab/sierra-local#77]
```python
>>> from sierralocal.hivdb import HIVdb
>>> from sierralocal.main import scorefile
>>> input_file = r'tests\hxb2-pr.fa'
>>> algorithm = HIVdb()
searching path .\sierra-local\sierralocal\data\HIVDB*.xml
searching path .\sierra-local\sierralocal\data\apobec*.tsv
HIVdb version 8.8
>>> scorefile(r'tests\hxb2-pr.fa', algorithm) 
Found NucAmino binary .\sierralocal\bin\nucamino-windows-amd64.exe
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".\sierralocal\main.py", line 47, in scorefile
    result = aligner.align_file(input_file)
  File ".\sierralocal\nucaminohook.py", line 178, in align_file
    result = json.load(self.reader(p.stdout))
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
https://github.com/PoonLab/sierra-local/blob/e060fb99a3457563be5a1b4c27084966f4582157/sierralocal/nucaminohook.py#L170-L182

**Comment by GopiGugan** [comment]
@SandeepThokala is using the `dev` branch to run the test suite. However, the `dev` branch isn't up to date. Created a PR to update `dev` branch. #78. This should resolve the issue
